#include "engine_DevelopmentCard.hpp"

#include <array>

#include "util_General.hpp"

namespace engine {

std::array<DevelopmentCard::Internal, 40> const DevelopmentCard::kLevel0{
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(1, 1, 1, 1, 0)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(1, 2, 1, 1, 0)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(2, 2, 0, 1, 0)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(0, 0, 1, 3, 1)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(0, 0, 2, 1, 0)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(2, 0, 2, 0, 0)),
    DevelopmentCard::Internal(Color::kBlack, 0, Gemset(0, 0, 3, 0, 0)),
    DevelopmentCard::Internal(Color::kBlack, 1, Gemset(0, 4, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(1, 0, 1, 1, 1)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(1, 0, 1, 2, 1)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(1, 0, 2, 2, 0)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(0, 1, 3, 1, 0)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(1, 0, 0, 0, 2)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(0, 0, 2, 0, 2)),
    DevelopmentCard::Internal(Color::kBlue, 0, Gemset(0, 0, 0, 0, 3)),
    DevelopmentCard::Internal(Color::kBlue, 1, Gemset(0, 0, 0, 4, 0)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 1, 1, 1, 1)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 1, 2, 1, 1)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 2, 2, 0, 1)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(3, 1, 0, 0, 1)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 0, 0, 2, 1)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 2, 0, 0, 2)),
    DevelopmentCard::Internal(Color::kWhite, 0, Gemset(0, 3, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kWhite, 1, Gemset(0, 0, 4, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(1, 1, 0, 1, 1)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(1, 1, 0, 1, 2)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(0, 1, 0, 2, 2)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(1, 3, 1, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(2, 1, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(0, 2, 0, 2, 0)),
    DevelopmentCard::Internal(Color::kGreen, 0, Gemset(0, 0, 0, 3, 0)),
    DevelopmentCard::Internal(Color::kGreen, 1, Gemset(0, 0, 0, 0, 4)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(1, 1, 1, 0, 1)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(2, 1, 1, 0, 1)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(2, 0, 1, 0, 2)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(1, 0, 0, 1, 3)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(0, 2, 1, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(2, 0, 0, 2, 0)),
    DevelopmentCard::Internal(Color::kRed, 0, Gemset(3, 0, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 1, Gemset(4, 0, 0, 0, 0)),
};

std::array<DevelopmentCard::Internal, 30> const DevelopmentCard::kLevel1{
    DevelopmentCard::Internal(Color::kBlack, 1, Gemset(3, 2, 2, 0, 0)),
    DevelopmentCard::Internal(Color::kBlack, 1, Gemset(3, 0, 3, 0, 2)),
    DevelopmentCard::Internal(Color::kBlack, 2, Gemset(0, 1, 4, 2, 0)),
    DevelopmentCard::Internal(Color::kBlack, 2, Gemset(0, 0, 5, 3, 0)),
    DevelopmentCard::Internal(Color::kBlack, 2, Gemset(5, 0, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kBlack, 3, Gemset(0, 0, 0, 0, 6)),
    DevelopmentCard::Internal(Color::kBlue, 1, Gemset(0, 2, 2, 3, 0)),
    DevelopmentCard::Internal(Color::kBlue, 1, Gemset(0, 2, 3, 0, 3)),
    DevelopmentCard::Internal(Color::kBlue, 2, Gemset(5, 3, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kBlue, 2, Gemset(2, 0, 0, 1, 4)),
    DevelopmentCard::Internal(Color::kBlue, 2, Gemset(0, 5, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kBlue, 3, Gemset(0, 6, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kWhite, 1, Gemset(0, 0, 3, 2, 2)),
    DevelopmentCard::Internal(Color::kWhite, 1, Gemset(2, 3, 0, 3, 0)),
    DevelopmentCard::Internal(Color::kWhite, 2, Gemset(0, 0, 1, 4, 2)),
    DevelopmentCard::Internal(Color::kWhite, 2, Gemset(0, 0, 0, 5, 3)),
    DevelopmentCard::Internal(Color::kWhite, 2, Gemset(0, 0, 0, 5, 0)),
    DevelopmentCard::Internal(Color::kWhite, 3, Gemset(6, 0, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 1, Gemset(3, 0, 2, 3, 0)),
    DevelopmentCard::Internal(Color::kGreen, 1, Gemset(2, 3, 0, 0, 2)),
    DevelopmentCard::Internal(Color::kGreen, 2, Gemset(4, 2, 0, 0, 1)),
    DevelopmentCard::Internal(Color::kGreen, 2, Gemset(0, 5, 3, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 2, Gemset(0, 0, 5, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 3, Gemset(0, 0, 6, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 1, Gemset(2, 0, 0, 2, 3)),
    DevelopmentCard::Internal(Color::kRed, 1, Gemset(0, 3, 0, 2, 3)),
    DevelopmentCard::Internal(Color::kRed, 2, Gemset(1, 4, 2, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 2, Gemset(3, 0, 0, 0, 5)),
    DevelopmentCard::Internal(Color::kRed, 2, Gemset(0, 0, 0, 0, 5)),
    DevelopmentCard::Internal(Color::kRed, 3, Gemset(0, 0, 0, 6, 0)),
};

std::array<DevelopmentCard::Internal, 20> const DevelopmentCard::kLevel2{
    DevelopmentCard::Internal(Color::kBlack, 3, Gemset(3, 3, 5, 3, 0)),
    DevelopmentCard::Internal(Color::kBlack, 4, Gemset(0, 0, 0, 7, 0)),
    DevelopmentCard::Internal(Color::kBlack, 4, Gemset(0, 0, 3, 6, 3)),
    DevelopmentCard::Internal(Color::kBlack, 5, Gemset(0, 0, 0, 7, 3)),
    DevelopmentCard::Internal(Color::kBlue, 3, Gemset(3, 0, 3, 3, 5)),
    DevelopmentCard::Internal(Color::kBlue, 4, Gemset(7, 0, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kBlue, 4, Gemset(6, 3, 0, 0, 3)),
    DevelopmentCard::Internal(Color::kBlue, 5, Gemset(7, 3, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kWhite, 3, Gemset(0, 3, 3, 5, 3)),
    DevelopmentCard::Internal(Color::kWhite, 4, Gemset(0, 0, 0, 0, 7)),
    DevelopmentCard::Internal(Color::kWhite, 4, Gemset(3, 0, 0, 3, 6)),
    DevelopmentCard::Internal(Color::kWhite, 5, Gemset(3, 0, 0, 0, 7)),
    DevelopmentCard::Internal(Color::kGreen, 3, Gemset(5, 3, 0, 3, 3)),
    DevelopmentCard::Internal(Color::kGreen, 4, Gemset(0, 7, 0, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 4, Gemset(3, 6, 3, 0, 0)),
    DevelopmentCard::Internal(Color::kGreen, 5, Gemset(0, 7, 3, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 3, Gemset(3, 5, 3, 0, 3)),
    DevelopmentCard::Internal(Color::kRed, 4, Gemset(0, 0, 7, 0, 0)),
    DevelopmentCard::Internal(Color::kRed, 4, Gemset(0, 3, 6, 3, 0)),
    DevelopmentCard::Internal(Color::kRed, 5, Gemset(0, 0, 7, 3, 0)),
};

}  // namespace engine